#!/usr/bin/perl
#
#


use warnings;
use strict;

use 5.010;

use lib './lib';

#
# PERL INCLUDES
#
use AnyEvent;
use Data::Dumper;
use YAML::Tiny;

#
# SAFP INCLUDES
#
use SAFP::Watcher;
use SAFP::Writer;

#
# GLOBALS
#

my $bookmarks = {};
my $config    = {};
my $watchers  = [];
my $writers   = [];

#
# MAIN
#

# read config

if( @ARGV && -r $ARGV[0] ) {
  # only using the first section
  $config = YAML::Tiny->read($ARGV[0])->[0];
}

# TODO: some initial defaults to be replaced with optional and mandatory
# config checking later on

$config->{listener} //= [];
$config->{sender} //= [];

$config->{cache}{type}     //= "cache";
$config->{cache}{separate} //= 0;
$config->{cache}{path}     //= '/tmp';

#
# validate config
if( ! @{ $config->{watchers} } ) {
  say("No watchers are configured.");
  exit(1);
}

if( ! @{ $config->{writers} } ) {
  say("No writers are configured.");
  exit(1);
}

# load the bookmarks
say "Loading bookmarks ...";
#$cache_watcher->load_bookmarks();

#
# build the writers 
say "Building writer(s) ...";

foreach my $s ( @{ $config->{writers} } ) {
  continue if( ! defined($s->{type}) );

  my $writer = SAFP::Writer->new($s, $config->{cache});
  $writer->add_bookmark_store($bookmarks);

  push( @{ $writers }, $writer );
}

#
# build the cache
say "Building cache ...";

# setup cache directory
if( ! -d -w -r $config->{cache}{path} ) {
  say("Cache directory does not exist or is not readable/writable: " . $config->{cache}{path});
  exit(1);
}

my $cache_writer = SAFP::Writer->new($config->{cache});

#
# build the watchers
say "Building watcher(s) ...";

sub reading {
  my $reader = shift;
  my $data = shift;

  # cache information
  $cache_writer->write($data);

}

foreach my $l ( @{ $config->{watchers} } ) {
  continue if( ! defined($l->{type}) );

  my $watcher = SAFP::Watcher->new($l);

  $watcher->add_bookmark_store( $bookmarks );
  $watcher->add_reader( \&reading );

  push( @{ $watchers }, $watcher );
}

#
# setup the signal handlers
my $exit_cv = AE::cv;

my $quit = sub {
  $exit_cv->send();
};

my $cv_term = AE::signal TERM => $quit;
my $cv_hup  = AE::signal HUP  => $quit;
my $cv_int  = AE::signal INT  => $quit;

#
# start the event loop
say "Initialised.";

$exit_cv->recv();

#
# cleanup, saving bookmarks on exit
say "\nSaving the bookmark.";

say Dumper($bookmarks);

#$cache_watcher->save_bookmarks();

exit 0;
